# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Free Trial(2)(45022478-3b08-4cb1-97fe-d68890029ac3)'
    subscriptionId: '45022478-3b08-4cb1-97fe-d68890029ac3'
    location: 'East US'
    templateLocation: 'URL of the file'
    deploymentMode: 'Incremental'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
